global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml-platform'
    static_configs:
      - targets: ['host.docker.internal:8000', 'host.docker.internal:8001', 'host.docker.internal:8002']
